// Step 1: Create Action Types
export const UPDATE_KING = "UPDATE_KING";
export const UPDATE_KING_METADATA = "UPDATE_KING_METADATA";
export const UPDATE_KING_BATTLE_RATINGS_LINE_DATA = "UPDATE_KING_BATTLE_RATINGS_LINE_DATA";
export const UPDATE_KING_BATTLE_WIN_LOSS_PIE_CHART_DATA = "UPDATE_KING_BATTLE_WIN_LOSS_PIE_CHART_DATA";
export const UPDATE_KING_BATTLE_DETAILS_TABLE_DATA = "UPDATE_KING_BATTLE_DETAILS_TABLE_DATA";
export const UPDATE_BATTLE_STATS_TABLE_DATA = "UPDATE_BATTLE_STATS_TABLE_DATA";
export const UPDATE_BATTLE_STATS_COLUMN_CHART_DATA = "UPDATE_BATTLE_STATS_COLUMN_CHART_DATA";




